name: PHPUnit Tests
on: [push]
jobs:
  run-phpstan:
    name: Run PHPUnit
    runs-on: ubuntu-latest
    steps:

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: dom, json, mbstring, psr, xdebug
        tools: composer:v2

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get Composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Connect downloaded dependencies with a cache in GitHub
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        # Note: Normally, we'd use the composer.lock to generate a hash,
        # but the lock file is currently not versioned.
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist

    - name: Run PHPUnit
      run: vendor/bin/phpunit
